#ifndef MATRIX_SIMD_AARCH64_H_
#define	MATRIX_SIMD_AARCH64_H_

#define MATRIX_ROWS_OFFSET      0
#define MATRIX_COLUMNS_OFFSET   4
#define MATRIX_LENGTH_OFFSET    8
#define MATRIX_ARRAY_OFFSET     12
#define MATRIX_SIZE             20

#endif // MATRIX_SIMD_AARCH64_H_